#!/bin/bash

set -eu
source "$(readlink -f "$0" | xargs dirname)/common.sh"

git checkout -b enh-codespell

if [ -e .github ]; then
    # do workflow first since straightforward
    cat > .github/workflows/codespell.yml << EOF
---
name: Codespell

on:
  push:
    branches: [$branch]
  pull_request:
    branches: [$branch]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Codespell
        uses: codespell-project/actions-codespell@v1
EOF
    git add .github/workflows/codespell.yml
    git commit -m "Add github action to codespell $branch on push and PRs"
else
    echo "No .github directory, no workflow provided"   
fi

skips=".git,*.pdf,*.svg"
for d in venv .venv venvs .tox versioneer.py package-lock.json; do
    if [ -e "$d" ]; then
        skips+=",$d"
    fi
done

# Then config file as the "last" commit we can amend if needed
cat > .codespellrc <<EOF
[codespell]
skip = $skips
# ignore-words-list = 
EOF

git add .codespellrc
git commit -m 'Add rudimentary .codespellrc' .codespellrc

codespell || {
echo
echo "Problematic?:"
echo
codespell | grep ','
}
