#!/bin/bash

set -eu
source "$(readlink -f "$0" | xargs dirname)/common.sh"

codespell_version_full=$(codespell --version)
codespell_version=${codespell_version_full//.dev$/}

if [[ "$codespell_version_full" =~ \.dev ]]; then
	# for the action we
	codespell_dir=$(python -c 'import codespell_lib as l; print(l.__path__[0])')
	codespell_version=$(
		git -C "$codespell_dir" describe --tags --match 'v[0-9]*' | sed -e 's,-.*,,g' -e 's,^v,,g'
	)
	echo "WARNING! Running development version $codespell_version_full."
	echo "         For the action etc we will mention tagged version $codespell_version".
fi

git checkout -b enh-codespell

if [ -e .github ]; then
    # do workflow first since straightforward
    cat > .github/workflows/codespell.yml << EOF
---
name: Codespell

on:
  push:
    branches: [$branch]
  pull_request:
    branches: [$branch]

permissions:
  contents: read

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
EOF
    git add .github/workflows/codespell.yml
    git commit -m "Add github action to codespell $branch on push and PRs"
else
    echo "No .github directory, no workflow provided"
fi

skips=".git,*.pdf,*.svg"
for d in venv .venv venvs .tox versioneer.py package-lock.json; do
    if [ -e "$d" ]; then
        skips+=",$d"
    fi
done

if [ -e pyproject.toml ]; then
	config="pyproject.toml"
	cat >> pyproject.toml <<EOF

[tool.codespell]
skip = '$skips'
#
# ignore-words-list = ''
EOF
else
	config=".codespellrc"
	# Then config file as the "last" commit we can amend if needed
	cat > .codespellrc <<EOF
[codespell]
skip = $skips
#
# ignore-words-list =
EOF
fi

echo "Config in $config"
git add "$config"
git commit -m 'Add rudimentary codespell config' "$config"

if [ -e .pre-commit-config.yaml ]; then
	# add pre-commit configuration there
	cat >> .pre-commit-config.yaml <<EOF

- repo: https://github.com/codespell-project/codespell
  rev: v${codespell_version}
  hooks:
  - id: codespell
EOF

	if [ "$config" = "pyproject.toml" ]; then
		cat >> .pre-commit-config.yaml <<EOF
    additional_dependencies:
      - tomli
EOF
	fi
	git add .pre-commit-config.yaml
	git commit -m 'Add pre-commit definition for codespell'
fi

codespell || {
echo
echo "Problematic?:"
echo
codespell | grep ','
}
