#!/bin/bash

set -eu

# needs to be specific to not include zsh and some people do odd /usr/bin/env bash things
SHEBANG_REGEX='^#\( *shellcheck \|!\(/bin/\|/usr/bin/env \)\(sh\|bash\|dash\|ksh\)\)'
WORKFLOW=.github/workflows/shellcheck.yml

if ! git grep "$SHEBANG_REGEX"; then
    echo "No shell scripts found, no need"
    exit 0
fi

source "$(readlink -f "$0" | xargs dirname)/common.sh"

function doit() {
	git grep -l "$SHEBANG_REGEX" | grep -v '\.\(txt\|md\)' | xargs shellcheck "$@"
}

function generate_workflow() {
	# we might need to overload branch if we already have it and just updating
	if [ -e "$WORKFLOW" ]; then
		branch_=$(sed -n -e '/branches:/s,.*\[\(.*\)\].*,\1,gp' "$WORKFLOW" | uniq)
		if [ -n "$branch_" ]; then
			branch="$branch_"
		fi
	fi
	cat > "$WORKFLOW" << EOF
---
name: Shellcheck

on:
  push:
    branches: [$branch]
  pull_request:
    branches: [$branch]

jobs:
  shellcheck:
    name: Check shell scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y shellcheck
      - name: shellcheck
        run: |
          git grep -l '$SHEBANG_REGEX' | xargs shellcheck
EOF
}

# poor man shortcuts for just doing it using the regex etc
case "${1:-}" in
	doit) shift; doit "$@"; exit $?;;
	generate_workflow) generate_workflow; exit $?;;
esac

if [ -e "$WORKFLOW" ]; then
    echo "$WORKFLOW already exists -- we must be good"
    exit 0
fi

git checkout -b enh-shellcheck

generate_workflow
git add "$WORKFLOW"
git commit -m "Add github action to shellcheck $branch on push and PRs"


doit
